---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-8.4

suites:
  - name: default
    run_list:
      - recipe[t3-mysql::default]
    attributes:
